"""
Builds a comparative summary table by reading all metricas.json and config.json
files available under ResultadosGenerativos/TimeGAN_condicional/.

Can be run at any point, including while run_all_patients.py is still running,
it aggregates whichever runs have already completed. Re-run at any time to get
an updated snapshot.
"""

import argparse
import json
import re
from pathlib import Path

import pandas as pd

RESULTS_BASE = Path("ResultadosGenerativos") / "TimeGAN_condicional"

# Only include runs generated by run_all_patients.py.
# Pattern: vae_wgan_wiener02_{config_suffix}_patient{id}
ORCHESTRATOR_RUN_PATTERN = re.compile(r"^vae_wgan_wiener02_(norm|recovery_none)_patient(\d+)$")


def collect_runs():
    """Walks all run_* folders under each patient_* and extracts config + metrics."""
    rows = []

    if not RESULTS_BASE.exists():
        print(f"Directory {RESULTS_BASE} not found. Have you run any training yet?")
        return rows

    for patient_dir in sorted(RESULTS_BASE.glob("patient_*")):
        for run_dir in sorted(patient_dir.glob("run_*")):
            run_name = run_dir.name.removeprefix("run_")

            if not ORCHESTRATOR_RUN_PATTERN.match(run_name):
                # Skip runs not generated by the orchestrator
                continue

            config_path  = run_dir / "config.json"
            metrics_path = run_dir / "metricas.json"

            if not config_path.exists():
                continue  # incomplete run

            if not metrics_path.exists():
                print(f"Warning: {run_dir.name} has config.json but metricas.json is missing "
                      f"(run may have been interrupted during training or evaluation).")
                continue

            with open(config_path) as f:
                config = json.load(f)
            with open(metrics_path) as f:
                metrics = json.load(f)

            row = {
                "patient_id":          config.get("patient_id"),
                "run_name":            config.get("run_name"),
                "recovery_activation": config.get("recovery_activation", "tanh"),
                "wiener_sigma":        config.get("wiener_sigma"),
                # Marginal fidelity
                "ks_statistic":        metrics["marginales"]["ks_statistic"],
                "wasserstein_mgdl":    metrics["marginales"]["wasserstein_mgdl"],
                # Temporal fidelity
                "acf_mae":             metrics["temporales"]["acf_mae"],
                "psd_l1_log":          metrics["temporales"]["psd_l1_log"],
                # Clinical metrics (real vs synthetic)
                "tir_real":            metrics["clinicas"]["real"]["tir"],
                "tir_synt":            metrics["clinicas"]["synt"]["tir"],
                "tar_real":            metrics["clinicas"]["real"]["tar"],
                "tar_synt":            metrics["clinicas"]["synt"]["tar"],
                "tbr_real":            metrics["clinicas"]["real"]["tbr"],
                "tbr_synt":            metrics["clinicas"]["synt"]["tbr"],
                "std_real_mgdl":       metrics["clinicas"]["real"]["std_mgdl"],
                "std_synt_mgdl":       metrics["clinicas"]["synt"]["std_mgdl"],
                # Utility metrics
                "discriminative_auc":  metrics["discriminative"]["auc_mean"],
                "predictive_gap_mgdl": metrics["predictive"]["predictive_gap_mgdl"],
            }
            rows.append(row)

    return rows


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--output", default="multipatient_validation_results.csv",
        help="Output CSV path (default: multipatient_validation_results.csv)"
    )
    args = parser.parse_args()

    rows = collect_runs()

    if not rows:
        print("No completed runs found. Run run_all_patients.py first, "
              "or wait for at least one run to finish.")
        return

    df = pd.DataFrame(rows)
    df = df.sort_values(["recovery_activation", "patient_id"]).reset_index(drop=True)

    # Warn if any (patient_id, recovery_activation) combination appears more than once
    dup_mask = df.duplicated(subset=["patient_id", "recovery_activation"], keep=False)
    if dup_mask.any():
        print("Warning: duplicate (patient, config) combinations detected:")
        print(df.loc[dup_mask, ["patient_id", "recovery_activation", "run_name"]].to_string(index=False))
        print("This may indicate run_* folders from different sessions with similar names.")
        print()

    df.to_csv(args.output, index=False)
    print(f"Table saved to {args.output}  ({len(df)} runs found).")

    n_patients_per_config = df.groupby("recovery_activation")["patient_id"].nunique()
    for cfg, n in n_patients_per_config.items():
        if n != 12:
            print(f"Warning: config '{cfg}' has {n} patients (expected 12 for a complete batch).")

    print()
    print("Summary by configuration (mean ± std across available patients):")
    print("─" * 70)
    summary = df.groupby("recovery_activation")[
        ["ks_statistic", "wasserstein_mgdl", "acf_mae", "psd_l1_log",
         "tbr_synt", "std_synt_mgdl", "discriminative_auc", "predictive_gap_mgdl"]
    ].agg(["mean", "std", "count"])
    print(summary.to_string())
    print()
    print("Note: 'count' reflects how many patients have completed runs so far. "
          "Re-run this script after more runs finish to get an updated summary.")


if __name__ == "__main__":
    main()
